require("configs.plugins.themes")
require("configs.plugins.gitsigns")
require("configs.plugins.neogit")
require("configs.plugins.neo-tree")
require("configs.plugins.lspconfig")
require("configs.plugins.conform")
